disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length

included: # paths to include during linting. `--path` is ignored if present.
- RxSSDP

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
