language: objective-c
os: osx
osx_image: xcode10.2
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=RxSSDP.xcworkspace
  - SCHEME=RxSSDP
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone XS"
script:
  - ./Pods/SwiftLint/swiftlint
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean -workspace "$WORKSPACE" -scheme "$SCHEME" | xcpretty
  - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty